"""Repository/infrastructure protocols — the seams of the architecture.

The application layer depends ONLY on these interfaces. Implementations:

    JobRepository    -> infrastructure.persistence.file_job_repository.FileJobRepository
                        (PostgresJobRepository is the planned durable upgrade)
    ArtifactStore    -> infrastructure.storage.local_artifact_store.LocalArtifactStore
                        (S3ArtifactStore / RustFS: same protocol, tranche 2)

Implementations must satisfy the contract tests in
backend_tests/test_statelessness.py / test_artifact_store.py so the
application layer behaves identically no matter which is injected.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Iterator, Protocol, runtime_checkable

from .entities import Job, utc_now


# ---------------------------------------------------------------------------
# JobRepository
# ---------------------------------------------------------------------------


@runtime_checkable
class TaskQueue(Protocol):
    """Dispatches job execution.

    Implementations:
      * InlineTaskQueue  — runs the handler in a worker thread immediately
        (development; equivalent behavior to FastAPI BackgroundTasks);
      * the "external" mode has NO in-API queue at all: the durable job
        record IS the queue entry and ``backend.app.worker`` claims it.

    Dispatch is a performance/ownership concern — correctness never
    depends on the same process dispatching and executing a job.
    """

    def add_task(self, fn, /, *args, **kwargs) -> None: ...


@runtime_checkable
class JobRepository(Protocol):
    """Durable store of Job records.

    Invariants every implementation must honor:
      * authoritative state lives in the repository, not in any process's
        memory — two instances constructed against the same backing store
        observe the same jobs (statelessness test B);
      * terminal states are locked: a mutation that tries to move a
        terminal job is refused and the record is unchanged;
      * a cancelled job can only end cancelled;
      * non-terminal jobs whose durable liveness signal expired are
        finalized honestly (JOB_INTERRUPTED) on read — never stuck.
    """

    def create(self, scene_id: str) -> Job: ...

    def get(self, job_id: str) -> Job | None: ...

    def list_for_scene(self, scene_id: str) -> list[Job]: ...

    def get_latest_for_scene(self, scene_id: str) -> Job | None: ...

    def get_active_for_scene(self, scene_id: str) -> Job | None: ...

    def update(
        self,
        job_id: str,
        *,
        status: str | None = None,
        stage: str | None = None,
        progress: float | None = None,
        result: dict[str, Any] | None = None,
        error: dict[str, Any] | None = None,
        message: str | None = None,
    ) -> Job | None: ...

    def request_cancel(self, job_id: str) -> Job | None: ...

    def renew_lease(self, job_id: str) -> Job | None: ...

    def list_queued(self) -> list[Job]:
        """All claimable queued jobs across scenes (worker discovery)."""
        ...

    def claim_queued(self, job_id: str) -> Job | None:
        """Atomically-as-possible claim: queued → processing. Returns the
        claimed job, or None when the job is no longer claimable (claimed
        by another worker, cancelled, expired, or unknown)."""

    def delete(self, job_id: str) -> bool: ...

    def delete_for_scene(self, scene_id: str) -> int: ...


# ---------------------------------------------------------------------------
# ArtifactStore
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ArtifactRef:
    """An opaque, backend-generated address of a stored artifact.

    Keys are generated by the BACKEND (never trusted from a client) and
    are the only artifact identity business logic deals in — no raw
    filesystem paths or bucket URLs leak into application code.
    """

    key: str


@dataclass
class ArtifactMetadata:
    key: str
    size: int
    content_type: str
    checksum_sha256: str
    created_at: str = field(default_factory=utc_now)


@runtime_checkable
class ArtifactStore(Protocol):
    """Byte storage for persistent artifacts.

    Invariants:
      * keys are validated (relative, no traversal, canonical);
      * writes are atomic — a reader never observes a partial artifact;
      * the store may be local (development) or object storage
        (S3/RustFS, production) — identical behavior per the contract
        tests.
    """

    def put_bytes(
        self, key: str, data: bytes, content_type: str = "application/octet-stream"
    ) -> ArtifactRef: ...

    def get_bytes(self, key: str) -> bytes: ...

    def open(self, key: str) -> Iterator[bytes]: ...

    def exists(self, key: str) -> bool: ...

    def delete(self, key: str) -> bool: ...

    def metadata(self, key: str) -> ArtifactMetadata: ...

    def list(self, prefix: str) -> list[str]: ...
