"""
Mock backend for the DepthWizard jury demo — serves precomputed scene bundles
generated by tools/generate_demo_bundles.py (tools/demo_bundles/<scene_id>/).

Covers the full frontend flow with zero live inference:
  upload -> processing (simulated staged job) -> results/depth/dsm/reference ->
  validation metrics + error map -> 3D terrain (heightmap/texture/minimap) ->
  elevation probe, height/slope measurements -> Route Assist (assess + heatmap) ->
  exports.

Endpoints (prefix /api/v1 unless noted):
  GET  /health
  POST /scenes                          (multipart; picks a bundle by filename hint)
  GET  /scenes, GET/DELETE /scenes/{id}
  POST /scenes/{id}/validate
  POST /scenes/{id}/process             -> job; GET /jobs/{job_id} polls staged progress
  POST /jobs/{job_id}/cancel
  GET  /scenes/{id}/results, /depth, /dsm, /reference, /validation,
       /validation/error-map, /terrain, /minimap, /elevation, /terrain/tiles
  GET  /scenes/{id}/results/{preview|rgb|dsm|depth|error-map|heightmap|
         dsm-texture|texture|slope|minimap|reference|reference-preview|passability}
  POST /scenes/{id}/measure/height, /measure/slope
  POST /scenes/{id}/route/assess; GET /scenes/{id}/route/heatmap
  GET  /scenes/{id}/export/{dsm|depth|validation|terrain}

Run:
  python tools/generate_demo_bundles.py   # once (bundles are checked in)
  python tools/mock_backend_for_camera_test.py [port]   # default :8000

Point the frontend at it:  VITE_API_BASE_URL=http://localhost:8000/api/v1
Upload a file whose name contains ridge/valley/quarry to pick that demo scene;
any other name round-robins through the bundles.
"""
import json
import math
import re
import sys
import threading
import time
import uuid
from collections import defaultdict
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlparse

import numpy as np

TOOLS_DIR = Path(__file__).resolve().parent
BUNDLE_DIR = TOOLS_DIR / "demo_bundles"
SIZE = 256
SIM_SECONDS = 7.0  # simulated processing duration

STAGES = [
    (0.00, "queued", "Queued"),
    (0.05, "validating", "Validating input"),
    (0.18, "preprocessing", "Preprocessing tiles"),
    (0.34, "depth_inference", "Depth inference"),
    (0.62, "calibration", "Metric calibration"),
    (0.74, "dsm_generation", "DSM generation"),
    (0.86, "terrain_generation", "Terrain generation"),
    (0.93, "validation", "Validating against reference"),
    (0.99, "finalizing", "Finalizing outputs"),
]

PNG_TYPES = {
    "preview", "rgb", "dsm", "depth", "error-map", "minimap", "slope",
    "reference", "reference-preview", "dsm-texture", "texture", "heatmap", "passability",
}
FILE_ALIASES = {
    "texture": "dsm_texture", "reference-preview": "reference_preview",
    "error-map": "error_map", "dsm-texture": "dsm_texture",
}


def load_bundles():
    bundles = {}
    for d in sorted(BUNDLE_DIR.iterdir()):
        if not (d / "scene.json").is_file():
            continue
        payload = json.loads((d / "scene.json").read_text())
        bundles[d.name] = {
            "payload": payload,
            "dsm": np.load(d / "dsm.npy"),
            "files": {
                f.stem: f.read_bytes()
                for f in d.iterdir()
                if f.suffix == ".png" or f.name == "heightmap.f32"
            },
        }
    return bundles


BUNDLES = load_bundles()
RR_ORDER = ["demo_ridge", "demo_valley", "demo_quarry"]
_rr = {"i": 0}

VEHICLE_SLOPE = {  # key -> (max slope deg, caution fraction of max)
    "fire_truck": 15.0, "ambulance": 12.0, "rescue_atv": 30.0,
    "suv_4x4": 20.0, "rescue_chopper": 45.0,
}

JOBS = {}
SCENES = defaultdict(dict)  # scene_id -> {"bundle": str}


class DemoError(Exception):
    def __init__(self, code, message, status=400):
        self.code, self.message, self.status = code, message, status


def pick_bundle(filename):
    name = (filename or "").lower()
    for key in RR_ORDER:
        hint = key.replace("demo_", "")
        if hint in name or hint.rstrip("s") in name:
            return key
    key = RR_ORDER[_rr["i"] % len(RR_ORDER)]
    _rr["i"] += 1
    return key


def job_state(job):
    if job["cancelled"]:
        return {
            "job_id": job["job_id"], "scene_id": job["scene_id"],
            "status": "cancelled", "stage": "cancelled", "progress": job["progress"],
            "message": "Cancelled by user", "cancel_requested": True,
            "result": None, "error": None,
        }
    frac = min(1.0, (time.time() - job["start"]) / SIM_SECONDS)
    lo, stage, msg = STAGES[-1]
    for f, s, m in STAGES:
        if frac >= f:
            lo, stage, msg = f, s, m
    progress = round(min(100.0, frac * 100.0), 1)
    if frac >= 1.0:
        return {
            "job_id": job["job_id"], "scene_id": job["scene_id"],
            "status": "completed", "stage": "completed", "progress": 100.0,
            "message": "Done", "cancel_requested": False,
            "result": {"scene_id": job["scene_id"], "outputs": ["rgb", "depth", "dsm", "terrain", "validation"]},
            "error": None,
        }
    return {
        "job_id": job["job_id"], "scene_id": job["scene_id"],
        "status": "processing", "stage": stage, "progress": progress,
        "message": msg, "cancel_requested": job["cancel_requested"],
        "result": None, "error": None,
    }


def elevation_at(bundle, x, y):
    xi = int(max(0, min(SIZE - 1, round(x))))
    yi = int(max(0, min(SIZE - 1, round(y))))
    return float(bundle["dsm"][yi, xi])


def slope_deg_between(bundle, x0, y0, x1, y1):
    p = bundle["payload"]
    georef = p["create"]["georeference"]
    px = (georef["pixel_width"] or 1.0)
    dz = elevation_at(bundle, x1, y1) - elevation_at(bundle, x0, y0)
    dx = math.hypot(x1 - x0, y1 - y0) * px
    return math.degrees(math.atan2(abs(dz), max(dx, 1e-6))), dz, dx


def route_assess(bundle, start, end, vehicles):
    p = bundle["payload"]
    px = p["create"]["georeference"]["pixel_width"] or 1.0
    n = 48
    xs = np.linspace(start["x"], end["x"], n)
    ys = np.linspace(start["y"], end["y"], n)
    path = [{"x": int(x), "y": int(y)} for x, y in zip(xs, ys)]
    dsm = bundle["dsm"]
    path_length_px = float(np.hypot(np.diff(xs), np.diff(ys)).sum())
    path_length_m = path_length_px * px
    slopes = []
    for i in range(n - 1):
        dz = abs(float(dsm[int(ys[i + 1]), int(xs[i + 1])] - dsm[int(ys[i]), int(xs[i])]))
        dx = math.hypot(xs[i + 1] - xs[i], ys[i + 1] - ys[i]) * px
        slopes.append(math.degrees(math.atan2(dz, max(dx, 1e-6))))
    max_slope = max(slopes) if slopes else 0.0
    max_step = float(np.abs(np.diff(dsm[np.clip(ys.astype(int), 0, SIZE - 1), np.clip(xs.astype(int), 0, SIZE - 1)])).max()) * 1.0
    out = []
    for v in vehicles:
        if v not in VEHICLE_SLOPE:
            continue
        limit = VEHICLE_SLOPE[v]
        frac_bad = sum(1 for s in slopes if s > limit) / max(1, len(slopes))
        if v == "rescue_chopper":
            verdict = "CAN_GO"
            reasons = ["Aerial path unconstrained by terrain slope"]
        elif max_slope <= limit * 0.6 and frac_bad == 0:
            verdict = "CAN_GO"
            reasons = ["Max slope on straight path within vehicle limit"]
        elif max_slope <= limit:
            verdict = "CAUTION"
            reasons = [f"Max slope {max_slope:.1f}° exceeds 60% of the {limit:.0f}° vehicle limit on some segments"]
        else:
            verdict = "CANNOT_GO"
            reasons = [f"Max slope {max_slope:.1f}° exceeds the {limit:.0f}° vehicle limit"]
        entry = {
            "vehicle": v,
            "vehicle_label": v.replace("_", " ").title(),
            "verdict": verdict,
            "reasons": reasons,
            "limits": {"max_slope_deg": limit, "max_step_m": 0.5},
            "path": path if verdict != "CANNOT_GO" else None,
            "path_length_m": round(path_length_m, 1),
            "path_length_px": round(path_length_px, 1),
            "max_slope_on_path_deg": round(max_slope, 1),
            "max_step_on_path_m": round(float(max_step), 2),
            "caution_fraction": round(frac_bad, 3),
            "estimated_travel_seconds": round(path_length_m / (3.0 if v != "rescue_chopper" else 20.0), 1),
            "detour_pixel": None,
            "snapped": {"start": False, "end": False},
            "landing_zone": None,
            "path_geojson": None,
        }
        if v == "rescue_chopper":
            # nearest low-slope landing zone to the goal
            best, bd = None, 1e9
            for yy in range(0, SIZE, 8):
                for xx in range(0, SIZE, 8):
                    patch = dsm[max(0, yy - 2):yy + 3, max(0, xx - 2):xx + 3]
                    s = math.degrees(math.atan2(float(patch.max() - patch.min()), 10 * px))
                    if s < 12.0:
                        d = math.hypot(xx - end["x"], yy - end["y"])
                        if d < bd:
                            bd, best = d, (xx, yy, s)
            if best:
                entry["landing_zone"] = {
                    "pixel": {"x": best[0], "y": best[1]},
                    "slope_deg": round(best[2], 1),
                    "distance_to_goal_px": round(bd, 1),
                    "distance_to_goal_m": round(bd * px, 1),
                }
        out.append(entry)
    return {
        "scene_id": p["create"]["scene_id"],
        "start_pixel": {"x": int(start["x"]), "y": int(start["y"])},
        "end_pixel": {"x": int(end["x"]), "y": int(end["y"])},
        "units": "m",
        "georeferenced": p["create"]["georeference"]["available"],
        "disclaimer": "Mock demo assessment — indicative only, not for operational use.",
        "path_crs": p["create"]["georeference"]["crs"],
        "vehicles": out,
    }


class Handler(BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):
        pass

    # -- plumbing -------------------------------------------------------------
    def _send(self, code, body, ctype="application/json"):
        data = body if isinstance(body, bytes) else json.dumps(body).encode()
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(data)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Headers", "Authorization, Content-Type")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, DELETE, OPTIONS")
        self.end_headers()
        self.wfile.write(data)

    def _err(self, status, code, message):
        self._send(status, {"error": {"code": code, "message": message, "details": None, "recoverable": True}})

    def _json_body(self):
        n = int(self.headers.get("Content-Length") or 0)
        raw = self.rfile.read(n) if n else b""
        return json.loads(raw) if raw else {}

    def _scene_bundle(self, sid):
        if sid not in SCENES:
            if sid.lower().replace("_", "").startswith("scene042"):
                # frontend's built-in "View Demo" scene id -> ridge bundle
                SCENES[sid] = {"bundle": "demo_ridge"}
            else:
                raise DemoError("SCENE_NOT_FOUND", f"Unknown scene {sid}", 404)
        return BUNDLES[SCENES[sid]["bundle"]]

    def _payload(self, sid):
        return self._scene_bundle(sid)["payload"]

    def _sub(self, obj, sid):
        return json.loads(json.dumps(obj).replace("{sid}", sid))

    def do_OPTIONS(self):
        self._send(204, b"", "text/plain")

    # -- routing --------------------------------------------------------------
    def do_GET(self):
        try:
            u = urlparse(self.path)
            path, q = u.path, parse_qs(u.query)
            m = re.match(r"^/api/v1/scenes/([^/]+)(?:/(.*))?$", path)
            if path == "/api/v1/health":
                return self._send(200, {"status": "ok", "version": "mock-demo", "model_loaded": True})
            mj = re.match(r"^/api/v1/jobs/([^/]+?)(?:/cancel)?$", path)
            if mj:
                job = JOBS.get(mj.group(1))
                if not job:
                    return self._err(404, "JOB_NOT_FOUND", mj.group(1))
                return self._send(200, job_state(job))
            if path == "/api/v1/scenes":
                return self._send(200, [
                    {"scene_id": sid, "filename": self._payload(sid)["filename"],
                     "status": "completed", "has_results": True, "created_at": "2026-09-24T00:00:00Z"}
                    for sid in SCENES
                ])
            if not m:
                return self._err(404, "NOT_FOUND", path)
            sid, rest = m.group(1), m.group(2) or ""
            if not rest:
                return self._send(200, self._sub(self._payload(sid)["create"], sid) | {"created_at": "2026-09-24T00:00:00Z", "updated_at": "2026-09-24T00:00:00Z", "metadata": {}})
            sub = self._sub
            if rest == "results":
                return self._send(200, sub(self._payload(sid)["results"], sid))
            if rest == "depth":
                return self._send(200, sub(self._payload(sid)["depth_meta"], sid))
            if rest == "dsm":
                return self._send(200, sub(self._payload(sid)["dsm_meta"], sid))
            if rest == "reference":
                return self._send(200, sub(self._payload(sid)["reference_meta"], sid))
            if rest == "validation":
                return self._send(200, sub(self._payload(sid)["validation"], sid))
            if rest == "validation/error-map":
                return self._send(200, sub(self._payload(sid)["error_map"], sid))
            if rest == "terrain":
                return self._send(200, sub(self._payload(sid)["terrain"], sid))
            if rest == "terrain/tiles":
                return self._err(404, "NOT_SUPPORTED", "tiled terrain not in mock")
            if rest == "minimap":
                return self._send(200, sub(self._payload(sid)["minimap"], sid))
            if rest == "elevation":
                b = self._scene_bundle(sid)
                x = float(q.get("x", ["0"])[0]); y = float(q.get("y", ["0"])[0])
                return self._send(200, {
                    "scene_id": sid, "x": x, "y": y,
                    "elevation": round(elevation_at(b, x, y), 2), "units": "m",
                    "slope_deg": round(slope_deg_between(b, x, y, x + 1, y)[0], 1),
                })
            if rest.startswith("results/"):
                return self._serve_file(sid, rest.split("/", 1)[1], q)
            if rest == "route/heatmap":
                b = self._scene_bundle(sid)
                vehicle = q.get("vehicle", ["fire_truck"])[0]
                stats = b["payload"]["heatmap"].get(vehicle, b["payload"]["heatmap"]["fire_truck"])
                return self._send(200, {
                    "scene_id": sid, "vehicle": vehicle,
                    "url": f"/api/v1/scenes/{sid}/results/heatmap",
                    "format": "png", "georeferenced": b["payload"]["create"]["georeference"]["available"],
                    **stats,
                })
            if rest.startswith("export/"):
                return self._serve_export(sid, rest.split("/", 1)[1])
            return self._err(404, "NOT_FOUND", path)
        except DemoError as e:
            return self._err(e.status, e.code, e.message)

    def _serve_file(self, sid, name, q):
        b = self._scene_bundle(sid)
        if name == "passability":
            key = "passability"
        else:
            key = FILE_ALIASES.get(name, name)
            if name == "heatmap":
                key = "heatmap"
        data = b["files"].get(key)
        if data is None:
            return self._err(404, "FILE_NOT_FOUND", name)
        ctype = "image/png"
        return self._send(200, data, ctype)

    def _serve_export(self, sid, kind):
        b = self._scene_bundle(sid)
        if kind == "dsm":
            # image/png so the results dashboard can render it directly in <img>
            return self._send(200, b["files"]["dsm"], "image/png")
        if kind == "depth":
            return self._send(200, (b["dsm"] - b["dsm"].min()).astype(np.float32).tobytes(), "application/octet-stream")
        if kind == "validation":
            return self._send(200, json.dumps(self._sub(b["payload"]["validation"], sid), indent=2).encode())
        if kind == "terrain":
            return self._send(200, json.dumps(self._sub(b["payload"]["terrain"], sid), indent=2).encode())
        return self._err(404, "NOT_FOUND", kind)

    # -- POST -----------------------------------------------------------------
    def do_POST(self):
        try:
            path = urlparse(self.path).path
            ctype = self.headers.get("Content-Type", "")
            if path == "/api/v1/scenes":
                body = self._read_multipart_filename(ctype)
                key = pick_bundle(body["filename"])
                sid = f"demo_{uuid.uuid4().hex[:10]}"
                SCENES[sid] = {"bundle": key}
                p = self._sub(BUNDLES[key]["payload"], sid)
                return self._send(201, p["create"])
            m = re.match(r"^/api/v1/scenes/([^/]+)/(.+)$", path)
            if not m:
                return self._err(404, "NOT_FOUND", path)
            sid, rest = m.group(1), m.group(2)
            self._scene_bundle(sid)  # 404 if unknown
            if rest == "validate":
                p = self._payload(sid)
                return self._send(200, {
                    "scene_id": sid, "valid": True, "issues": [],
                    "warnings": [], "errors": [],
                    "recommendations": [] if p["create"]["georeference"]["available"] else ["No georeferencing: outputs will be in relative scene units."],
                    "georeferenced": p["create"]["georeference"]["available"],
                    "dimensions": p["create"]["dimensions"],
                })
            if rest == "process":
                body = self._json_body()
                job_id = f"job_{uuid.uuid4().hex[:10]}"
                JOBS[job_id] = {"job_id": job_id, "scene_id": sid, "start": time.time(),
                                "cancel_requested": False, "cancelled": False, "progress": 0.0}
                return self._send(202, {"job_id": job_id, "scene_id": sid, "status": "queued", "stage": "queued", "progress": 0.0})
            if rest == "refine":
                job_id = f"job_{uuid.uuid4().hex[:10]}"
                JOBS[job_id] = {"job_id": job_id, "scene_id": sid, "start": time.time(),
                                "cancel_requested": False, "cancelled": False, "progress": 0.0}
                return self._send(202, {"job_id": job_id, "scene_id": sid, "status": "queued", "stage": "queued", "progress": 0.0})
            if rest == "measure/height":
                b = self._scene_bundle(sid)
                body = self._json_body()
                g, t = body["ground"], body["top"]
                return self._send(200, {
                    "scene_id": sid,
                    "ground_elevation": round(elevation_at(b, g["x"], g["y"]), 2),
                    "top_elevation": round(elevation_at(b, t["x"], t["y"]), 2),
                    "height_m": round(elevation_at(b, t["x"], t["y"]) - elevation_at(b, g["x"], g["y"]), 2),
                    "units": "m",
                })
            if rest == "measure/slope":
                b = self._scene_bundle(sid)
                body = self._json_body()
                a, c = body["point_a"], body["point_b"]
                deg, dz, dx = slope_deg_between(b, a["x"], a["y"], c["x"], c["y"])
                return self._send(200, {
                    "scene_id": sid, "slope_deg": round(deg, 1),
                    "slope_percent": round(math.tan(math.radians(deg)) * 100, 1),
                    "distance_m": round(dx, 2), "elevation_change_m": round(dz, 2), "units": "m",
                })
            if rest == "route/assess":
                b = self._scene_bundle(sid)
                body = self._json_body()
                return self._send(200, route_assess(b, body["start"], body["end"], body.get("vehicles", [])))
            if re.match(r"^jobs/([^/]+)/cancel$", rest):
                job = JOBS.get(rest.split("/")[1])
                if not job:
                    return self._err(404, "JOB_NOT_FOUND", rest)
                job["cancel_requested"] = True
                job["cancelled"] = True
                return self._send(200, {"job_id": job["job_id"], "scene_id": job["scene_id"],
                                        "status": "cancelled", "cancel_requested": True})
            if rest == "mosaic":
                return self._err(400, "MOSAIC_UNSUPPORTED", "Mock does not support mosaic")
            return self._err(404, "NOT_FOUND", path)
        except DemoError as e:
            return self._err(e.status, e.code, e.message)

    def _read_multipart_filename(self, ctype):
        n = int(self.headers.get("Content-Length") or 0)
        raw = self.rfile.read(n)
        m = re.search(rb'filename="([^"]+)"', raw)
        return {"filename": m.group(1).decode() if m else "upload.tif"}

    # -- DELETE ---------------------------------------------------------------
    def do_DELETE(self):
        path = urlparse(self.path).path
        m = re.match(r"^/api/v1/scenes/([^/]+)$", path)
        if m and m.group(1) in SCENES:
            SCENES.pop(m.group(1))
            return self._send(200, {"deleted": m.group(1)})
        return self._err(404, "NOT_FOUND", path)


def main():
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 8000
    print(f"Demo mock backend on http://localhost:{port} — bundles: {', '.join(BUNDLES)}")
    print(f"  ({len(BUNDLES)} bundles loaded; pick via upload filename containing ridge/valley/quarry)")
    ThreadingHTTPServer(("0.0.0.0", port), Handler).serve_forever()


if __name__ == "__main__":
    main()
